### ISSUE TITLE
Address pylint errors

### ISSUE THREAD

**Issue by victor-wildlife** [ocean-data-factory-sweden/kso_utils#172]
The pylint tests for kso_utils reports the following errors that we should address:
widgets

- [x] kso_utils/widgets.py:108:32: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)
- [x] kso_utils/widgets.py:290:0: E0102: function already defined line 68 (function-redefined)
- [x] kso_utils/widgets.py:305:0: E0102: function already defined line 83 (function-redefined)

yolo utils

- [x] kso_utils/yolo_utils.py:509:8: E0611: No name 'get_movie_url' in module 'kso_utils.server_utils' (no-name-in-module)
- [x] kso_utils/yolo_utils.py:1300:13: E1101: Module 'ipywidgets' has no 'BBoxWidget' member (no-member)
- [x] kso_utils/yolo_utils.py:1462:13: E1101: Module 'ipywidgets' has no 'BBoxWidget' member (no-member)

project
- [x] kso_utils/project.py:73:25: E1101: Instance of 'ProjectProcessor' has no 'mount_snic' member (no-member)
- [x] kso_utils/project.py:679:24: E1101: Instance of 'ProjectProcessor' has no 'local_sites_csv' member (no-member)
- [x] kso_utils/project.py:767:8: E1123: Unexpected keyword argument 'generate_export' in function call (unexpected-keyword-arg)
- [x] kso_utils/project.py:767:8: E1120: No value for argument 'project' in function call (no-value-for-parameter)
- [x] kso_utils/project.py:1312:4: E0213: Method 'transfer_model' should have "self" as first argument (no-self-argument)
- [x] kso_utils/project.py:1585:23: E1136: Value 'self.run_history' is unsubscriptable (unsubscriptable-object)

server
- [x] kso_utils/server_utils.py:211:9: E0602: Undefined variable 'server' (undefined-variable)
- [x] kso_utils/server_utils.py:247:25: E0602: Undefined variable 'movie_path' (undefined-variable)
- [x] kso_utils/server_utils.py:253:25: E0602: Undefined variable 'movie_path' (undefined-variable)

project_utils
- [x] kso_utils/project_utils.py:84:19: E1120: No value for argument 'Project_name' in constructor call (no-value-for-parameter)

Spyfish
- [x] kso_utils/spyfish_utils.py:117:8: E1111: Assigning result of a function call, where the function has no return (assignment-from-no-return)

**Comment by victor-wildlife** [comment]
@jannesgg where do we use the "transfer_model" function that we create in project.py? I couldn't find it in the code

**Comment by Diewertje11** [comment]
I unchecked the server_utils errors, because I still get those in MR #166 .
