### ISSUE TITLE
Clean tut#5,6,7 functions of project.py

### ISSUE THREAD

**Issue by victor-wildlife** [ocean-data-factory-sweden/kso_utils#179]
I am not sure what these six functions (inside the project processor) do. Can we remove them?

![Image](https://user-images.githubusercontent.com/55268669/266873075-049d3ca2-5e86-4a51-86fa-e01ee063983d.png)

**Comment by Diewertje11** [comment]
I am not sure what they do either. 
* get_team_name is not used anywhere, so I think it should be save to remove
* get_ml_data: we also have a different function with this name in server_utils, which is used in tutorial 5. But this one in project.py is not used.
* process_image: not used
* prepare_movies: not uses
* Check_frames_uploaded: Not used, in project.py we do call t_utils.check_frames_uploaded, which does not exist. and we do define a check_frames uploaded in zooniverse_utils, which is used inside the zooniverse_utils. So this one in project.py we can remove and we should check which one the t_utils should be, if it should reverse to the one in zooniverse_utils or not. 

So I think we can remove them all, and should only look for check_frames_uploaded which function the t_utils.check_frames_uploaded should be.
This is a mistake that pylint should have detected, and for unknown reason it does not. See issue 241

**Comment by Diewertje11** [comment]
The new pylint implementation in MR #181 fixes the issue of that check_frames_uploaded from t_utils was not recognised as an error!

**Comment by jannesgg** [comment]
@victor-wildlife @Diewertje11 Feel free to remove those methods which are not called. They were probably part of skeleton code that I wanted to fill earlier but never got around to removing.
